name: 'Auto sync Reviewers with Assignees'
description: 'Synchronize the list of reviewers with the list of assignees on a PR'
inputs:
  token:
    description: 'Github token'
    required: true
    default: 'default'
  exclude:
    description: 'List of Github logins to be ignored during synchronization, separated by a comma'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'  
  color: 'purple'